version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/apartment_finder
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=your_super_secret_jwt_key_here_make_it_long_and_random
      - SECRET_KEY=your_super_secret_key_for_password_hashing
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=apartment_finder
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  celery:
    build: .
    command: celery -A app.core.celery worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/apartment_finder
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=your_super_secret_jwt_key_here_make_it_long_and_random
      - SECRET_KEY=your_super_secret_key_for_password_hashing
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
